---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloworld-dev
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  project: default
  source:
    repoURL: https://github.com/mathianasj-backstage/helloworld-quarkus
    targetRevision: HEAD
    path: .helm/chart
    helm:
      valueFiles:
        - ../value-files/values-dev.yaml
      values: |
        quarkus-run: 
          image:
            tag: da912c6919d7bfba602fa13bb36bfdeeef5f9093
          appName: eda-demo
          name: helloworld
  destination:
    server: https://kubernetes.default.svc
    namespace: eda-demo-dev
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true    
    retry:
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy 
  ignoreDifferences:      
  - group: networking.istio.io
    kind: VirtualService
    name: helloworld
    namespace: eda-demo-dev
    jsonPointers:
    - /spec/hosts
  - group: route.openshift.io/v1
    kind: Route
    namespace: knative-serving-ingress
